version: '3.5'

services:
    mariadb:
        build: ./requirements/mariadb/.
        container_name: mariadb
        image: mariadb:v8
        env_file:
            - .env
        restart: always
        volumes:
            - db:/var/lib/mysql/
        networks:
            - inception
    nginx:
        build: ./requirements/nginx/.
        container_name: nginx
        image: nginx:v8
        env_file:
            - .env
        ports:
            - '443:443'
        restart: on-failure
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html/
        networks:
            - inception
    wordpress:
        build: ./requirements/wordpress/.
        image: wordpress:v8
        container_name: wordpress
        env_file:
            - .env
        restart: always
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html/
        
        networks:
            - inception
    adminer:
        build: ./requirements/bonus/adminer/.
        image: adminer:v8
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - inception
volumes:
    db:
        driver: local
        driver_opts:
            device : $HOME/data/db
            type : none
            o: bind
    wordpress:
        driver: local
        driver_opts:
            device: $HOME/data/wordpress
            type: none
            o: bind
networks:
    inception:
        name: inception
